services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    # ports:
    #   - "11434:11434"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    runtime: nvidia
    shm_size: 8g
    networks:
      - curious_frame_network
  piper:
    build:
      context: ./piper_server
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    runtime: nvidia
    shm_size: 8g
    networks:
      - curious_frame_network

  curious-frame:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ollama
      - piper
    command: python3 -m curious_frame --ollama-url http://ollama:11434/api/chat --piper-url http://piper:5000
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    runtime: nvidia
    shm_size: 8g
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/snd:/dev/snd"
    volumes:
      - "/etc/enctune.conf:/etc/enctune.conf"
      - "/etc/nv_tegra_release:/etc/nv_tegra_release"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/run/user/1000/pulse:/run/user/1000/pulse"
      - "/tmp/argus_socket:/tmp/argus_socket"
    networks:
      - curious_frame_network

networks:
  curious_frame_network: {}
